### ISSUE TITLE
Looks good, but no save option? 

### ISSUE THREAD

**Issue by mostlycarbonite** [macbre/wayback-machine#11]
That's a shame.

**Comment by macbre** [comment]
@mostlycarbonite, what do you mean by _save option_?

**Comment by kalmi** [comment]
He probably means something like this: https://gist.github.com/atomotic/721aefe8c72ac095cb6e

**Comment by mostlycarbonite** [comment]
Yeah that's it, it would be nice if I could save a page from code.

**Comment by macbre** [comment]
@mostlycarbonite, you mean save as _save webpage snapshot in webarchive_? If so, that's not the purpose `wayback-machine` package was created - it's a client that reads the history.

**Comment by mostlycarbonite** [comment]
So this is "Closed, will not consider implementing"?

**Comment by macbre** [comment]
Yes, `wayback-machine` is a simple client that lets you fetch the list of all snapshots or just the latest one. Period :)
