### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by simonlovesyou** [macbre/wayback-machine#14]
I'm getting this error when using the module:
```
				matches[1], // e.g. rel
				       ^

TypeError: Cannot read property '1' of null
    at /project/node_modules/wayback-machine/lib/timemap.js:23:12
    at Array.map (native)
    at parseLine (/project/node_modules/wayback-machine/lib/timemap.js:19:3)
   ....
```

It seems to have problem to parse a line if it contains a `>` at the end of the line. Can be fixed by changing the `parseLineRegex` on line `6` in `timemap.js` from `/^(\w+)="(.*)"$/;` to `/^(\w+)="(.*)">?$/;`

Let me know if you want me to submit a pull-request with the changes!

**Comment by macbre** [comment]
@simonlovesyou , thanks for the bug report. Please submit a PR and update unit tests.

Can you provide the line that is affected by this issue?

**Comment by simonlovesyou** [comment]
I'll submit one soon @macbre 

>  Can be fixed by changing the `parseLineRegex` on line 6 in `timemap.js`
